spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
            authorization-grant-type: authorization_code
            client-name: kakao
          google:
            redirect-uri: 'http://localhost:8080/login/oauth2/code/google'
            scope : profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false #개발, 테스트 모드에서는 끕니다.
  profiles:
    active: dev
    include: secret

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sbb__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size=50  # 한번에 DB업로드 할 수 있는 최대 개수 지정
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: INFO
    com.ll.spring_additional: DEBUG  #패키지명
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
